////
prof. MATTEO RAVAIOLI

- Intestino
	- Anatomia e fisiologia dell'intestino tenue
	- Malattie del piccolo intestino, e tumori dell'ileo
	- Le malattie croniche infiammatorie dell'intestino (Crohn e RCU)
	- Principi di resezioni ed anastomosi intestinali. Complicanze. Tipi di stomie
	- I polipi ed i tumori del colon-retto
	- Classificazione, diagnosi e principi di terapia delle diverticoliti
- Surrene
	- Anatomia, fisiologia e fisio-patologia delle ghiandole surrenaliche
	- Ipercortisolismo, feocromocitoma, incidentalomi surrenalici
- Rene
	- Indicazioni, principi di tecnica e complicanze a breve e lungo termine del trapianto di rene
////

= Chirurgia gastroenterologica

== Trapianto di rene
* *Causa principale che rende trapianto necessario: insufficienza renale in dialisi fallita*
* Il trapianto di rene, rispetto alla dialisi, determina un netto aumento dell'aspettativa di vita e una migliore QoL

.Insufficienza renale: SeS
****
* Aspecifici → astenia, anoressia, anemia, poliuria, ipertensione
* Specifici → iperK, acidosi metabolica, iperazotemia, ↑ crea, ↑ uricemia [alito urinoso]

.Tipologie di dialisi
* *Dialisi peritoneale* → dialisi tramite catetere addominale a permanenza. Si fa di solito durante la notte in autonomia a casa, ma è meno efficace nel depurare il pz. (per cui si arriva ad un certo punto, con il progredire della patologia, in cui non è più efficace). Complicanze: infezioni, occlusioni intestinali, aderenze intestinali, inefficacia
* *Emodialisi* → dialisi tramite fistola arterio-venosa o, in subordine, tramite catetere vascolare a permanenza. Se si perde l'accesso vascolare è impossibile farla, e quando fatta a lungo termine determina una pessima QoL. Il grado di tolleranza alla dialisi dipende dal singolo pz.
****

=== Selezione del candidato

=== Selezione del donatore
* 2 tipi di donatore: vivo e cadavere (generalmente DBD; ma, per ampliare la platea disponibile, in centri specializzati si fa anche da DCD -- sebbene logisticamente sia estremamente più complicato)

=== Procedura chirurgica
* Sul donatore
	. Espianto (compresa arteria, vena e uretere)
	. Conservazione
	. Preparazione al trapianto
	** Rimozione del grasso perirenale
	** Accertamento della tenuta dei vasi
* Sul ricevente

=== Complicanze

==== Early

==== Late
