---
title: Farmacologia Generale e Speciale (C.I)
author: Emanuele Vicinelli
date: Aa 2023--2024 (2021--2022)
lang: it
self-contained: true
toc: true
format:
  html:
    mermaid-format: png
    html-math-method: webtex
---

<!-- Intro per capire la roba vera -->
{{< include farmacologia/farmaco-generale.md >}}

<!-- Principi di corretta prescrizione dei farmaci -->
{{< include farmacologia/prescrizione.md >}}

<!-- Ricerca e sviluppo di nuovi farmaci, principi di bioetica -->
{{< include farmacologia/RnD-bioetica.md >}}

<!-- La vera farmacologia -->
{{< include farmacologia/farmaco-speciale.md >}}

# {#refs}
1. []{#stoppstart} O’Mahony, Denis. **«STOPP/START Criteria for Potentially Inappropriate Medications/Potential Prescribing Omissions in Older People: Origin and Progress».** _Expert Review of Clinical Pharmacology_ 13, fasc. 1 (2 gennaio 2020): 15–22. <https://doi.org/10.1080/17512433.2020.1697676>
2. []{#drugresepil} Tang F, Hartz AMS, Bauer B. **Drug-Resistant Epilepsy: Multiple Hypotheses, Few Answers**. _Front Neurol. 2017 Jul 6;8:301_. doi: 10.3389/fneur.2017.00301. PMID: 28729850; PMCID: [PMC5498483](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5498483/)
3. []{#esc18htn} Bryan Williams, Giuseppe Mancia, Wilko Spiering, Enrico Agabiti Rosei, Michel Azizi et al. ESC Scientific Document Group, **2018 ESC/ESH Guidelines for the management of arterial hypertension: The Task Force for the management of arterial hypertension of the European Society of Cardiology (ESC) and the European Society of Hypertension (ESH)**, _European Heart Journal, Volume 39, Issue 33_, 01 September 2018, Pages 3021–3104, <https://doi.org/10.1093/eurheartj/ehy339>
4. []{#esc21chf} McDonagh, Theresa A, Marco Metra, Marianna Adamo, Roy S Gardner, Andreas Baumbach, Michael Böhm, Haran Burri, et al. 2021. **«2021 ESC Guidelines for the Diagnosis and Treatment of Acute and Chronic Heart Failure»**. _European Heart Journal 42_ (36): 3599–3726. <https://doi.org/10.1093/eurheartj/ehab368>
5. []{#glifozinefichissime} Braunwald, E. (2022). __Gliflozins in the Management of Cardiovascular Disease.__ In D. L. Longo (Ed.), _New England Journal of Medicine (Vol. 386, Issue 21, pp. 2024–2034)_. Massachusetts Medical Society. <https://doi.org/10.1056/nejmra2115011>
6. []{#jamaassoc} Dong, Y.-H., Chang, C.-H., Wang, J.-L., Wu, L.-C., Lin, J.-W., & Toh, S. (2020). __Association of Infections and Use of Fluoroquinolones With the Risk of Aortic Aneurysm or Aortic Dissection__. In _JAMA Internal Medicine (Vol. 180, Issue 12, p. 1587)_. American Medical Association (AMA). <https://doi.org/10.1001/jamainternmed.2020.4192>
